# Generated by Django 3.1.2 on 2021-03-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='newsdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NewsData.user'),
        ),
    ]
