# Generated by Django 3.1.2 on 2021-03-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsData', '0006_remove_newsdata_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='hashVal',
            field=models.BigIntegerField(default=56),
        ),
    ]
