# Generated by Django 3.1.2 on 2021-03-21 05:35

import NewsData.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsData', '0007_newsdata_hashval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='hashVal',
            field=models.BigIntegerField(default=5),
        ),
    ]
