# Generated by Django 3.1.2 on 2021-03-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsData', '0008_auto_20210321_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='hashVal',
            field=models.BigIntegerField(default=10),
        ),
    ]
