# Generated by Django 3.1.2 on 2021-03-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsData', '0010_auto_20210321_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='hashVal',
            field=models.BigIntegerField(blank=True),
        ),
    ]
