# Generated by Django 3.1.2 on 2021-03-27 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsData', '0012_auto_20210327_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
