# Generated by Django 3.1.2 on 2021-03-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsData', '0013_newsdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='author',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
